jobs:
  build:
    steps:
      - checkout
      - run: echo "This is a build step"    # similar to "script" in GitLab

  test:
    steps:
      - checkout
      - run: echo "This is a test step"

  oast:
    machine: true
    steps:
      - checkout

      - run:
          command: docker run --rm -v $(pwd):/src -w /src hysnsec/bundle-audit check --format json --output bundle-audit-output.json
          when: on_fail             # Even if the job fails, continue to the next stages

      - store_artifacts:
          path: bundle-audit-output.json
          destination: bundle-audit
          when: always

  integration:
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1

  prod:
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  rails:
    jobs:
      - build
      - test:
          requires:
            - build 
      - oast:
          requires:
            - test
      - integration:
          requires:
            - oast
      - prod:
          type: approval
          requires:
            - integration
